//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxes
    {
        public int ProductId { get; set; }
        public int Tax { get; set; }
    }
}
